### PR TITLE
Made Dashboard 2 functioning and write CSS

### PR DESCRIPTION
**Pull request by Jai0212**
- dashboard 2 works with placeholder data
- created the graph as well for dashboard 2
- wrote CSS for dashboard 2
- fixed tests running

### CODE REVIEW

**Comment by Navnoorsinghmahal** [comment]
Reviewed the code.

**Comment by armaganngul** [comment]
Placeholder data looks good to me. Will implement the API for model reading functionality.

**Comment by akshatoza1** [comment]
Looks good to me. Does the CSS for dashboard2 follow a similar template for dashboard1?

**Comment by tvirat** [comment]
Looks good to me

**Comment by Jai0212** [comment]
> Looks good to me. Does the CSS for dashboard2 follow a similar template for dashboard1?

Yea, the theme and the graph template are the same throughout

**Pull request merged**
