### PR TITLE
#64 updated readme

### PR DESCRIPTION
**Pull request by tvirat**
Update the readme file

# Acceptance Criteria:
- Include the important sections like credits, how to run, technical details and description of the project
- Include the Fair learn acknowledgement (https://fairlearn.org/v0.11/about/index.html#citing-fairlearn)

### CODE REVIEW

**Comment by Jai0212** [comment]
> Update the readme file
> 
> # Acceptance Criteria:
> * Include the important sections like credits, how to run, technical details and description of the project
> * Include the Fair learn acknowledgement (https://fairlearn.org/v0.11/about/index.html#citing-fairlearn)

I would recommend adding a LICENSE.txt file and put the license in that

**Comment by tvirat** [comment]
> > Update the readme file
> > # Acceptance Criteria:
> > 
> > * Include the important sections like credits, how to run, technical details and description of the project
> > * Include the Fair learn acknowledgement (https://fairlearn.org/v0.11/about/index.html#citing-fairlearn)
> 
> I would recommend adding a LICENSE.txt file and put the license in that

I have updated the README file and included a `license.txt` document.

**Comment by Jai0212** [comment]
> > > Update the readme file
> > > # Acceptance Criteria:
> > > 
> > > * Include the important sections like credits, how to run, technical details and description of the project
> > > * Include the Fair learn acknowledgement (https://fairlearn.org/v0.11/about/index.html#citing-fairlearn)
> > 
> > 
> > I would recommend adding a LICENSE.txt file and put the license in that
> 
> I have updated the README file and included a `license.txt` document.

Alright great! Everything else looks good!

**Comment by Jai0212** [comment]
Do mention about the integration of accessibility services as well

**Pull request merged**
